name: Build LLVM project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 1024
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: compile all
        run: bash compile.sh
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: llvm-10
          path: llvm-10